// C++ Standard Library headers
#include <iostream>
#include <algorithm>
#include <vector>
#include <string>
#include <cmath>
#include <map>
#include <set>
#include <queue>
#include <stack>
#include <deque>
#include <list>
#include <forward_list>
#include <bitset>
#include <complex>
#include <valarray>
#include <numeric>
#include <utility>
#include <functional>
#include <memory>
#include <new>
#include <iterator>
#include <locale>
#include <codecvt>
#include <chrono>
#include <tuple>
#include <type_traits>
#include <ratio>
#include <climits>
#include <cfloat>
#include <cstdint>
#include <cinttypes>
#include <limits>
#include <exception>
#include <stdexcept>
#include <cassert>
#include <cerrno>
#include <cctype>
#include <cwctype>
#include <cstring>
#include <cwchar>
#include <cstdlib>
#include <cstdio>
#include <ctime>
#include <cmath>

// Modern C++ headers (C++11 and later)
#include <array>
#include <unordered_map>
#include <unordered_set>
#include <initializer_list>
#include <scoped_allocator>
#include <typeindex>
#include <typeinfo>
#include <random>
#include <regex>
#include <atomic>
#include <thread>
#include <mutex>
#include <future>
#include <condition_variable>